### ISSUE TITLE
Cannot read model

### ISSUE THREAD

**Issue by Amogu** [AndrewBMartin/pygurobi#1]
Hello,
I am not sure this is an issue per se, but from the get go I get a module 'pygurobi' has no attribute 'read_model' error message. 

Thanks for your help.

**Comment by AndrewBMartin** [comment]
That's unexpected. Please include your Python version and the output of
>>> import pygurobi
>>> print pygurobi

**Comment by Amogu** [comment]
<module 'pygurobi' from '/Users/aoukair/py36Gurobi/lib/python3.6/site-packages/pygurobi/__init__.py'>

I am running Python 3.6.

Thanks.

**Comment by AndrewBMartin** [comment]
PyGurobi is written for Python 2. Unfortunately, a port to Python 3 is not planned. Please feel free to open a PR if you'd like to give it a try.

**Comment by Amogu** [comment]
I see that now. Thanks for the quick response. It is certainly worth having a Python 3 version.
